FROM golang:1.18 as production

RUN mkdir /app

WORKDIR /app

COPY . .

WORKDIR /app/hello

RUN go mod init hello

RUN go build


FROM scratch

COPY --from=production /app / 

WORKDIR /hello

ENTRYPOINT ["./hello"]